### ISSUE TITLE
unnecessary delay in readBytes()

### ISSUE THREAD

**Issue by kaido42** [karpy47/php-mqtt-client#21]
```
	        // Wait a while before trying to read again (in micro seconds)
	        usleep($this->socketReadDelay * 1000);
```

this code is unnecessary and adds long delays when receiving longer messages.

As the socket is in blocking mode, the fread() call blocks until it can read at least one byte. In case of timeout, it returns no data.

**Comment by karpy47** [comment]
In theory you're right, but I could not get the stream timeout to work at that time and had to resort to another timeout. Haven't spent time on the issue since then, but know it solved a problem. We could just add a setter-method for the socketReadDelay and set it to zero as an optional way to skip the delay.
Have you tested if the fread stream timeout works?
