### ISSUE TITLE
Using getPublishMessages method problem

### ISSUE THREAD

**Issue by My-Dev-Net** [karpy47/php-mqtt-client#35]
Hi
I have some missunderstanding of using `sendSubscribe` and `getPublishMessages` methods.
I need to recieve messages that subscribed, if they exist, and i don't need for waiting messages, if they are not still published by another program.
So i do the following:
Unsubscribing all and subscribing to 4 topics:

`$client->sendUnsubscribe(array("username/#"));`
`$res[] = $client->sendSubscribe("username/current");`
`$res[] = $client->sendSubscribe("username/status");`
`$res[] = $client->sendSubscribe("username/temperature");`
`$res[] = $client->sendSubscribe("username/humidity");`
In `$res` array i have all 4 topics with `["success"]=>bool(true)` and `["qosGiven"]=>int(1)`

Next trying different variants:
1) `$messages = $client->getPublishMessages()` - recieve all messages, but very slow and always "MQTT: Read timeout" in debug.
2) `$messages = $client->getPublishMessages(0)` - recieve only 3 messages (always all subscribed, but not last subscribed), fast and no timeout.
3) `$messages = $client->getPublishMessages(1)` - recieve 4 messages fast and no timeout.

So, what is the right and fastest method in my case ?

And so on, if i skip `sendUnsubscribe` calling before `sendSubscribe` and `getPublishMessages` methods in first variant, then i recieve more than 4 messages with duplicates.
For example, i recieve 2 "username/current" topics, that different with `["retain"]=>bool(true)` and `["retain"]=>bool(false)`.

If i use variant 3 and subscribe to absent topics, then also have duplicates of existing topics different with `["retain"]=>bool(true)` and `["retain"]=>bool(false)`, even if use `sendUnsubscribe`, slowly and sometimes with "MQTT: Read timeout"

**Comment by karpy47** [comment]
Hi,

I'm not actively using this package myself any longer and there is also a newer MQTT-standard since a while back, so I expect there are/will be some other package supporting that. Anyway, it should work for MQTT version 3 (check what version your message server uses). 

Regarding the 3 variants you tried. 
1. Sounds normal - this package is not async, so when there is nothing left to be read a timeout is the only way to proceed. The debug message of "MQTT: Read timeout" is exactly that and will happen after the timeout you set (default is 5000 ms).
2. Will attempt to read 0 messages from the stream, ie nothing should be returned, unless some messages have been queued. Then all those will be returned, which will happen without any timeouts as theses message already have been fetched from the stream. Seems like this is happening to you.
3. Will attempt to read 1 message from stream. If there is at least one message it will be fast (like in your case), otherwise there will be a timeout. Finally all messages queued from previous calls will be returned as well. (Which is why there are more than 1 message returned.)

In general I would try to use  `$client->getPublishMessages()` with a shorter timeout if you need to poll the stream often. Just set  a different timeout when connecting to the server. Syntax is: 
`sendConnect($clientId, $cleanSession=false, $keepAlive=10, $timeout=5000)`

Hope that helps.
